<a href="https://colab.research.google.com/github/KarWox/data_science-/blob/main/wprowadzenie_%20Python_podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=1

In [ ]:
b=2

In [ ]:
c=3

In [ ]:
print(a,b,c)

1 2 3


In [ ]:
my_value=32

In [ ]:
print(my_value)

32


Typy danych w Python Numbers, String, List



In [ ]:
a=1 

In [ ]:
b=4.5

In [ ]:
type(a)

int

In [ ]:
type(b)

float

In [ ]:
isinstance(a, int)

True

In [ ]:
my_string="tekst"

In [ ]:
my_string

'tekst'

In [ ]:
my_string[2]

'k'

In [ ]:
my_string[:6]

'tekst'

In [ ]:
my_string[2;5]

SyntaxError: ignored

In [ ]:
my_string[3:5]

'st'

In [ ]:
my_string2= "lulahulala"

In [ ]:
my_string + my_

NameError: ignored

In [ ]:
my_string + my_string2

'tekstlulahulala'

In [ ]:
name= "konkatenacja string"

In [ ]:
len(name)

19

In [ ]:
print(name.title())

Konkatenacja String


In [ ]:
s="WItaj"

In [ ]:
print(s.islower())

False


In [ ]:
print(s.find('w'))

-1


In [ ]:
print(s.find('W'))

0


In [ ]:
name=input("podaj imie: ")

podaj imie: Karol


In [ ]:
nem=input" POdaj swoje imie: "
print(nem)

SyntaxError: ignored

In [ ]:
nem=input(" POdaj swoje imie: ")
print(nem)

 POdaj swoje imie: Karol
Karol


In [ ]:
a=int(input("Wprowadzhasło: "))

Wprowadzhasło: w


ValueError: ignored

In [ ]:
a=int(input("Wprowadzhasło: "))

Wprowadzhasło: 345


In [ ]:
print(a)

345


In [ ]:
pcs=12

In [ ]:
s= "W magazynie"+ str(pcs) "sztuk"

SyntaxError: ignored

In [ ]:
pcs=23
s='W magazynie {} sztuk'.format(pcs)

In [ ]:
s

'W magazynie 23 sztuk'

In [ ]:
3=!2

SyntaxError: ignored

In [ ]:
1==1

True

In [ ]:
3=!2

SyntaxError: ignored

In [ ]:
1>2

False

In [ ]:
3!=2

True

In [ ]:
3!=3

False

In [ ]:
a="b"
b="a"

In [ ]:
print(a==b)

False


IF warunek 

In [ ]:
if 3==3

SyntaxError: ignored

In [ ]:
if 3==3:
  print ( "to jest prawda")

to jest prawda


In [ ]:
a=177
if a == 0:
  print( "Tak to  0")
else:
  print("nie to nie to ")

nie to nie to 


In [ ]:
name = input("POdaj swoje imie: ")

if len(name)<3:
  print( "Podaj minimum 3 znaki")
else:
  print(name)

POdaj swoje imie: ja
Podaj minimum 3 znaki


In [ ]:
name =input("podaj jezyk prgramowania")
if name == "python":
  print("pyhton")
elif name == "php":
  print("to jest php")
elif name == "java":
  print ("to jest java")
else:
  print("nie znam takiego jezyka")

podaj jezyk prgramowaniannn
nie znam takiego jezyka


In [ ]:
 a=4
 b=4
 if a==3 and b==4:
   print("Bingo, spelniony warunek")
else:
    print("To nie to ")

To nie to 


In [ ]:
a=2
b=2
c=7
if a!=2 and b==3 or c==5:
  print("Bingo")

**Loops in python: while and for and range function**


In [ ]:
# while warunek 
# zrób coś

Pętla nieskończona - błąd

In [ ]:
#while True:
# print("pętla działa!")

In [ ]:
counter = 0 

In [ ]:
counrter=0
while counrter < 10:
  print('counrter')
  counrter+=1

counrter
counrter
counrter
counrter
counrter
counrter
counrter
counrter
counrter
counrter


In [ ]:
counter = 0
while counter < 10:
  print (counter)
  counter+=1

0
1
2
3
4
5
6
7
8
9


break and continue


In [ ]:
counter = 0
while counter <= 10:
  counter+=1
  if counter %2 == 0:
    continue
  print(counter)

1
3
5
7
9
11


In [ ]:
while True:
  num= int(input('Podaj dowolną liczbe większą od zeroa'))
  if num >0:
    print("Twoja liczba to :", num)
    break
else:
  print("To nie jest prawidłowa liczba")


Podaj dowolną liczbe większą od zeroa3
Twoja liczba to : 3


In [ ]:
while True:
  num= int(input('Podaj dowolną liczbe większą od zeroa'))
  if num >0:
    print("Twoja liczba to :", num)
    break
else:
  print("To nie jest prawidłowa liczba")

Podaj dowolną liczbe większą od zeroa-3
Podaj dowolną liczbe większą od zeroa-4
Podaj dowolną liczbe większą od zeroa-4
Podaj dowolną liczbe większą od zeroa-5
Podaj dowolną liczbe większą od zeroa44
Twoja liczba to : 44


pętla for:

In [ ]:
# for wartość in zestaw wartości:
#   zrób coś z warością

In [ ]:
values=[1,2,3,4,5]

In [ ]:
for v in values:
  v+=
  print(v)

SyntaxError: ignored

In [ ]:
for v in values:
  print(v)

1
2
3
4
5


In [ ]:
for v in values:
  print(V+=1)

SyntaxError: ignored

In [ ]:
for v in values:
  if v <= 4:
    break
print(v)


1


In [ ]:
for v in range(1,20,6):
  print (v)

1
7
13
19


In [ ]:
for v in range (1,60,3)

SyntaxError: ignored

In [ ]:
for v in range (1,60,3):
  print ("*"*v)

*
****
*******
**********
*************
****************
*******************
**********************
*************************
****************************
*******************************
**********************************
*************************************
****************************************
*******************************************
**********************************************
*************************************************
****************************************************
*******************************************************
**********************************************************


struktury danych

lista 

In [ ]:
a=[2,3,4,5,6,7,8,8]

In [ ]:
a[0]

2

In [ ]:
print(a[3])

5


In [ ]:
a[3]

5

In [ ]:
my_list=[1,2,3,4]

In [ ]:
my_list[0]=20

In [ ]:
print my_list

SyntaxError: ignored

In [ ]:
print( my_list)

[20, 2, 3, 4]


In [ ]:
my_list= [10,20,30,40]
for v in my_list:
  print (v)

10
20
30
40


In [ ]:
my_list=[12,20,30,40]


In [ ]:
my_list.append(50)

In [ ]:
print(my_list)

[12, 20, 30, 40, 50]


In [ ]:
my_list[5]

IndexError: ignored

In [ ]:
print(my_list[5])

IndexError: ignored

In [ ]:
print(my_list[4])

50


In [ ]:
my_list.reverse()

In [ ]:
my_list

[50, 40, 30, 20, 12]

In [ ]:
my_list.appned[3,4,5,65]

AttributeError: ignored

In [ ]:
my_list.append(35)

In [ ]:
my_list

[50, 40, 30, 20, 12, 35]

In [ ]:
my_list.sort()

In [ ]:
my_list

[12, 20, 30, 35, 40, 50]

In [ ]:
print(my_list[0:2])

[12, 20]


In [ ]:
my_list2= [50,60]

In [ ]:
main_list= my_list + my_list2 

In [ ]:
print(main_list)

[12, 20, 30, 35, 40, 50, 50, 60]


In [ ]:
print(len(main_list))

8


In [ ]:
print(10 in main_list)

False


In [ ]:
my_list=[v for v in range(10,240) if v %2 == 1] 

In [ ]:
my_list

[11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149,
 151,
 153,
 155,
 157,
 159,
 161,
 163,
 165,
 167,
 169,
 171,
 173,
 175,
 177,
 179,
 181,
 183,
 185,
 187,
 189,
 191,
 193,
 195,
 197,
 199,
 201,
 203,
 205,
 207,
 209,
 211,
 213,
 215,
 217,
 219,
 221,
 223,
 225,
 227,
 229,
 231,
 233,
 235,
 237,
 239]

krotka - tuples
nie można modyfikować

In [ ]:
my_tuple=(1,2,3,4,5)

In [ ]:
my_tuple[2]

3

In [ ]:
my_tuple[3]=33

TypeError: ignored

In [ ]:
values = (1,2,3,4,'abc', true)

NameError: ignored

In [ ]:
values=(1,2,3,"abd",true)

NameError: ignored

In [ ]:
values=(1,2,3,"abd",True)

In [ ]:
values

(1, 2, 3, 'abd', True)

In [ ]:
values[3]

'abd'

In [ ]:
values

(1, 2, 3, 'abd', True)

In [ ]:
values.sort()

AttributeError: ignored

In [ ]:
values.count()

TypeError: ignored

In [ ]:
new_values = values[3:5]

In [ ]:
new_values

('abd', True)

In [ ]:
print(2 in values)

True


In [ ]:
print(new_values + (20,55))

('abd', True, 20, 55)


In [ ]:
my_list

()

In [ ]:
my_list

()

In [ ]:
my_list=[10,4,5,6,633,4,5,66]

In [ ]:
my_typle= tuple(my_list)

In [ ]:
len(my_tuple)

5

In [ ]:
my_tuple

(1, 2, 3, 4, 5)

In [ ]:
my_list

[10, 4, 5, 6, 633, 4, 5, 66]

In [ ]:
my_typle

(10, 4, 5, 6, 633, 4, 5, 66)

In [ ]:
len(my_typle)

8

In [ ]:
2 in my_typle

False

In [ ]:
max(my_typle)

633

In [ ]:
min(my_typle)

4

In [ ]:
sum(my_typle)

733

In [ ]:
my_typle

(10, 4, 5, 6, 633, 4, 5, 66)

In [ ]:
a,b,c,d,e,f = my_typle

ValueError: ignored

In [ ]:
a,b,c,d,e,f,g,h = my_typle

In [ ]:
a

10

In [ ]:
my_typle[1]

4

In [ ]:
b

4

# dictionary

zbiór wartości 

*   Ele
nie ma indeksument listy
*   Element listy


zawiera pary klucz-wartość
mutowalne



In [1]:
my_d={'a':1, 'b':2}

In [2]:
print(my_d['a'])

1


In [3]:
operation = {
    'env' : "production",
    'db':'mysql',
    'version': 1.0,
}

In [4]:
operation

{'db': 'mysql', 'env': 'production', 'version': 1.0}

In [5]:
operation[2]

KeyError: ignored

In [ ]:
operation[env]

In [ ]:
operation['env']

In [ ]:
operation['version']= 2.3

In [ ]:
print(version)

In [ ]:
print(operation)

In [ ]:
operation['VERSION']

In [ ]:
  operation['version']

In [ ]:
operation = {
    'env' : "production",
    'db':'mysql',
    'version': 1.0,
}

In [ ]:
del operation[]

In [ ]:
del operation['db']

In [ ]:
operation

In [ ]:
print(operation.get('db'))

In [ ]:
print(operation.get('version'))

dodawanie kilku par klucz wartość

In [ ]:
operation.update({
    'user':'admin',
    'app': 0
})

In [ ]:
operation

In [ ]:
for key in operation:
  print(operation[key])

In [ ]:
operation.values()

In [ ]:
operation.keys()

### set zbiór

In [ ]:
a=set()

In [ ]:
a

In [ ]:
type(s)

In [ ]:
type(a)

In [ ]:
a=set([1,2,3,4,32,2,3,4,2,121])

In [ ]:
a

In [ ]:
b=set([1,2,4,2,3.4,55454])

In [ ]:
print(a.intersection(b))

In [ ]:
print(a.union(b))

In [ ]:
print(a.difference(b))

In [ ]:
print(a.symmetric_difference(b))

NUMPY



In [ ]:
import numpy as np


In [ ]:
data= np.random.radn(2,3)

In [ ]:
data= np.random.rand(2,3)

In [ ]:
data

In [ ]:
data*10

In [ ]:
data.shape

In [ ]:
data.shape

In [ ]:
data.dtype

In [ ]:
data= [1,2,33,45,6,]

In [ ]:
import numpy as np

In [ ]:
arr= np.array(data)

In [ ]:
arr

In [ ]:
data2=[[1,2,3,4],[5,6,7,8]]

In [ ]:
arr2=np.array(data2)

In [ ]:
arr2

In [ ]:
arr2.ndim

In [ ]:
np.arange(17)

In [ ]:
a= np.arange(1,6,2)

In [ ]:
a

In [ ]:
a= np.zeros(1,12,3)

In [ ]:
b=np.zeros(15)

In [ ]:
b

In [ ]:
b=np.zeros((5,5,5))

In [ ]:
b

In [ ]:
b=np.eye((3,3))

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((4,10))

In [ ]:
np.zeros((1,10))dtype='int'

In [ ]:
np.zeros(shape=(5,5), dtype.'int')

In [ ]:
np.full((3,3), fill_value=4, dtype='int')

In [ ]:
np.arange(10)

In [ ]:
np.arange((5,15,5))

In [ ]:
np.arange(5,10,15)

In [ ]:
np.arange(5,15,5)

In [ ]:
np.arange((1,10,2),dtype='float')

In [ ]:
np.linspace(10,20,4)

In [ ]:
a=np.arange(15)

In [ ]:
a

In [ ]:
a.reshape(3,5)

In [ ]:
a.reshape(5,-1)

In [ ]:
a.reshape(-1,3)

In [ ]:
a.reshape(-1,5)

In [ ]:
a

In [ ]:
b=np.arange(15)

In [ ]:
a+b

In [ ]:
c=a+b

In [ ]:
c=a*b

In [ ]:
c

In [ ]:
a+4

In [ ]:
d=add(a+c)

In [ ]:
np.add(c,b)

In [ ]:
d=np.add(c,b)

In [ ]:
d

In [ ]:
d.reshape(4,4)

In [ ]:
d.reshape(-1,5)

In [ ]:
X= np.array([[1,2],[5,6]])
Y =np.array([[2,4],[8,9]])

In [ ]:
print(x,y)

In [ ]:
print(c)

In [ ]:
print(x)

In [ ]:
print(X)

In [ ]:
np.dot(X,Y)

In [ ]:
print(Y)

In [ ]:
np.random.seed(0)

In [ ]:
np.random.rand(10)

In [ ]:
np.random.rand(10,5)

In [ ]:
np.random.rand(10,2)

In [ ]:
np.random.randint(10)

In [ ]:
np.random.randint([4,3,2,3])

In [ ]:
np.random.choice(['python','java','sql'])

In [ ]:
data=np.arange(10)

In [ ]:
np.random.shuffle(data)

In [ ]:
data

itaracja po tablicach, maski

In [ ]:
d

In [ ]:
imponr nympy as np

In [ ]:
import numpy as np

In [ ]:
d

In [6]:
import numpy as np

In [7]:
A= np.arange(20)

In [8]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
A[2]

2

In [10]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
A = A.reshape(4,5)

In [13]:
A[0]

array([0, 1, 2, 3, 4])

In [14]:
A[1]

array([5, 6, 7, 8, 9])

In [15]:
A[:,1]

array([ 1,  6, 11, 16])

In [16]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A[[1,]]

array([[5, 6, 7, 8, 9]])

In [18]:
A[1,1]

6

In [20]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [21]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
for row in A:
  print(row[0])

0
5
10
15


In [25]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [26]:
A.spa ()

AttributeError: ignored

In [27]:
A.shape()

TypeError: ignored

In [28]:
A.shape

(4, 5)

In [29]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [32]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
a= arange(-10,10,0.5)

NameError: ignored

In [34]:
a= np.arange(-10,10,0.5)

In [35]:
a

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [36]:
A>0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
  A[A>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [39]:
np.bitwise_and(A>5, A<5)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])